spring:
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: admin
    password: admin
    publisher-returns: true
    virtual-host: /dev
  listener:
    direct:
      acknowledge-mode: manual
    simple:
      acknowledge-mode: manual
